### ISSUE TITLE
create list of URLs that need to always work

### ISSUE THREAD

**Issue by jovo** [neurodata/open-connectome#155]
this includes:

- links that davi has and needs
- links published in any of our pubs, including:
  - weiler pub
  - harris pub

**Comment by kunallillaney** [comment]
@jovo Should we move this to internal?

**Comment by jovo** [comment]
do you mean move this issue? sure.

**Comment by kunallillaney** [comment]
@jovo test.

**Comment by jovo** [comment]
ok
