### ISSUE TITLE
Some RESTful endpoint to gather public datasets

### ISSUE THREAD

**Issue by j6k4m8** [neurodata/open-connectome#183]
Currently, if I want to get a list of all public datasets (for [whatever reason](https://github.com/openconnectome/ocp-journal-paper/issues/8)) I have to scrape `public_tokens/`, read in every token name, then scrape the `[:token]/info/` page to find `dataset.description` which I can then add to a set of public datasets.

In [`ndio==0.0.20`](https://github.com/openconnectome/ndio/commit/48799732fa74f7535966f01ad0e4299a5a956547), this is extraordinarily slow (about 1m30s to complete), most of the time spent waiting for RESTful calls to finish. I don't know if this is a functionality anyone else is interested in (@jovo and @willgray could certainly comment on that) but it is an interesting function that we currently lack, that would answer questions like:

- "What tokens are available that are based on the `kasthuri11` dataset?"
- "Which dataset has had the most scientific attention (i.e. most tokens)?"
- "How many unique datasets do we hold?"

**Comment by jovo** [comment]
i agree that it would be useful, i disagree that 1m30s is particularly relevant.
we can store all that info in lims, and make it easier, or just deal with it.
no scientific results will ever depend on that being faster,
although i realize that it would be nice.

**Comment by kunallillaney** [comment]
This is now done and docs are here. https://raw.githubusercontent.com/neurodata/open-connectome/microns/docs/api/public_api.rst

**Comment by jovo** [comment]
:+1:
