### ISSUE TITLE
swc file support

### ISSUE THREAD

**Issue by jovo** [neurodata/open-connectome#20]
@randalburns @kunallillaney @willgray @gkiar
http://research.mssm.edu/cnic/swc.html
is the format that vaa3d and janelia are now using to store skeletons

**Comment by willgray** [comment]
Also compatible with neuromorph and the trees toolbox!




I like swc

**Comment by jovo** [comment]
@randalburns i think you built this already?

**Comment by kunallillaney** [comment]
I think this is done.

**Comment by jovo** [comment]
well, its in the microns branch.  does that count? it hasn't been tested yet...

**Comment by kunallillaney** [comment]
@jovo This is supposed to be on the current master branch. @randalburns added this sometime ago. If @gkiar thinks it is not done then we can open it again.
